---
responses:
  "That language is hurtful to people I care about.": 
    - '#uglygirlsarenotallowed'  
    - '#slut'
    - '#whore'
    - '#ihatefemaleswho'
    - '#mensrights'
    - '#fatbitch'
    - '#agoodwoman'
    - 
  "test":
    - '#uglygirlsarenotallowed'
